### ISSUE TITLE
.jscsrc does not appear to have any effect

### ISSUE THREAD

**Issue by jeromecovington** [globexdesigns/brackets-jscs#19]
Using this .jscsrc file on Ubuntu works great. It seems to be ignored on Mac OS 10.10.2. .jscs.json also appears to be ignored on that operating system. Using brackets release 1.2 build 1.2.0-15697 (release 8f82e2a97) build timestamp: Sun Feb 22 2015 22:34:50 GMT-0800

.jscs is in the project root, at the same level as .jshintrc
```
{
    "requireCurlyBraces": [
        "if",
        "else",
        "for",
        "while",
        "do",
        "try",
        "catch"
    ],
    "requireOperatorBeforeLineBreak": true,
    "requireCamelCaseOrUpperCaseIdentifiers": true,
    "maximumLineLength": {
      "value": 80,
      "allowComments": true,
      "allowRegex": true
    },
    "validateIndentation": "\t",
    "validateQuoteMarks": "'",

    "disallowMultipleLineStrings": true,
    "disallowMixedSpacesAndTabs": true,
    "disallowTrailingWhitespace": true,
    "disallowSpaceAfterPrefixUnaryOperators": true,
    "disallowMultipleVarDecl": false,
    "disallowKeywordsOnNewLine": ["else"],

    "requireSpaceAfterKeywords": [
      "if",
      "else",
      "for",
      "while",
      "do",
      "switch",
      "return",
      "try",
      "catch"
    ],
    "requireSpaceBeforeBinaryOperators": [
        "=", "+=", "-=", "*=", "/=", "%=", "<<=", ">>=", ">>>=",
        "&=", "|=", "^=", "+=",

        "+", "-", "*", "/", "%", "<<", ">>", ">>>", "&",
        "|", "^", "&&", "||", "===", "==", ">=",
        "<=", "<", ">", "!=", "!=="
    ],
    "requireSpaceAfterBinaryOperators": true,
    "requireSpacesInConditionalExpression": true,
    "requireSpaceBeforeBlockStatements": true,
    "requireSpacesInForStatement": true,
    "requireLineFeedAtFileEnd": true,
    "requireSpacesInFunctionExpression": {
        "beforeOpeningCurlyBrace": true
    },
    "disallowSpacesInAnonymousFunctionExpression": {
        "beforeOpeningRoundBrace": true
    },
    "disallowSpacesInsideObjectBrackets": "all",
    "disallowSpacesInsideArrayBrackets": "all",
    "disallowSpacesInsideParentheses": true,

    "disallowMultipleLineBreaks": true,
    "disallowNewlineBeforeBlockStatements": true
}
```

Here is the brackets.json
```
{
    "themes.theme": "dark-theme",
    "me.drewh.jsbeautify.on_save": false,
    "linting.collapsed": false,
    "language": {
        "javascript": {
            "linting.prefer": [
                "JSHint",
                "JSCS"
            ],
            "linting.usePreferredOnly": true
        }
    },
    "useTabChar": true
}
```

**Comment by stefan-schweiger** [comment]
+1 it does also not work for me under windows, JSHint works just fine but JSCS does not display any errors defined in the settings file

**Comment by globexdesigns** [comment]
v0.3.0 was just pushed to the Brackets Extension registry which should resolve this issue.

**Comment by stefan-schweiger** [comment]
You might want to reopen this issue.

It still does not work for me, after updating the extension and restarting Brackets. JSHint stuff is shown for me, but JSCS still does not appear in the Interactive Linter.

Just to be sure I got everything right:

**brackets.json** (Application Preferences File)
```JSON
   ...
    "language": {
        "javascript": {
            "linting.prefer": ["JSHint", "JSCS"],
            "linting.usePreferredOnly": true
        }
    },
    ...
```

**.jscsrc** (In project root folder)
```JSON
{
    "disallowKeywordsOnNewLine": ["else"]
}
```

**somefile.js**
```JS
var x = 0;

if (x < 0) {
    x++;
}
else {
    x--;
}
```

**Comment by stefan-schweiger** [comment]
Ok it seems that, some other extension was messing with JSCS (works when I only have JSHint and JSCS installed), I will now try to enable them again one by one and give you some feedback.

**Comment by globexdesigns** [comment]
Hmm, yeah, I'm not sure what Interactive Linter does. Reference the issue you open with the author and maybe together we can find a solution.

**Comment by MiguelCastillo** [comment]
@stefan-schweiger thanks for reaching out. interactive linter is pretty invasive in the sense that it will remove any registered javascript linters. this is simple because of performance issues.  my take is that if you have interactive linter then having another linter running along side is not what you are looking for.

> let me clarify quickly that interactive linter is just a lint runner with a plugin ecosystem where you can create ur own linters.

with that said, I have just added support for defining what linter you want to run via brackets preferences. this gives you two options.

1. disable interactive linting for javascript. 
2. use jscs linter in interactive linter, which I have just revamped.

running interactive linter and another linter has caused confusion also because interactive linter also provides a linter panel at the bottom and it seems to have have confused some folks.

[Here](https://github.com/MiguelCastillo/Brackets-InteractiveLinter/tree/master/plugins/default) is a list of supported linters.

And you can add the following line to your global `brackets.json` or project `.brackets.json` to customize the linter:

```
{
    "interactive-linter.javascript": ["jscs"],
    "interactive-linter.coffeescript": ["coffeelint"]
}
```

jscs supports `.jscs.json`.  Also, you can disable interactive linter on a per language basis by setting the linter language to null. e.g.

```
{
    "interactive-linter.javascript": null,
    "interactive-linter.coffeescript": ["coffeelint"]
}
```

all the stuff about configuration is brand new and only in master... once documentation is added, I will be posting it to the brackets registry.

-- I am really not trying highjack this thread to promote interactive linter.  This is just in response to the issue that was logged for interactive linter.

**Comment by amamf** [comment]
I'm suffering from not being able to use 2 linters side by side that run one after another. The point is that jshint and jscs are aimed at a bit different goals, so it would be logically if I could use both, especially taking into account that "interactive-linter.javascript" is an array which implies that I can define more than one linter, but when I try to use both linters - "interactive-linter.javascript": ["jshint", "jscs"], only the first one works. If I for instance change that option to "interactive-linter.javascript": ["jscs", "jshint"], then only "jscs" will work.

**Comment by MiguelCastillo** [comment]
@amamf Yeah the long term is to allow multiple linters to run in interactive linter. But for right now only the first one runs, as you pointed out. Sorry for the confusion.  I am thinking of getting back to this in the next two weeks...  Really swamped with other stuff right now. :/
